name: VanillaBank
version: '${project.version}'
main: com.nethernetwork.vanillabank.VanillaBank
api-version: '1.21'
author: YourName
description: Integrates VanillaBank web application with Minecraft server.
commands:
  register:
    description: Generates a registration link for the web application.
    usage: /register 